#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Delete mesh if exist
if [ -d "constant/polyMesh" ] ; then
  rm -r constant/polyMesh
fi


#====================================
# Creates mesh inside the constant/triSurface/domainWedge.stl created in Step 1
# Requirments: cfMesh
# Controlled by the system/meshDict
# Note - All values for the centre of the boxes currently defined in the objectRefinement section of the meshDict are for a drop height H=0.09. Therefore, for other dropheights you should modify the values of         centre      (0 0 z); by the difference bettween H=0.09 and your drop height.
# - Also bear in mind that the mesh will be translated up by your drop height in Step 3. This is why the meshDict currently has the freeSurface boxes centered at (0 0 -0.09), because it will be translated up by 0.09 in Step 3 to make it finally centered at 0. 

runApplication cartesianMesh

