#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#==========================================
# Create domain box using gmsh and saves it as an stl file in constant/trisurface
# Requirements: gmsh
# Controlled by the wedgeMaker.geo file. 
# Adjust param[4] on line 7 to change the initial drop height

gmsh -2 -format stl wedgeMaker.geo -o constant/triSurface/domainWedge.stl > log.gmsh.domain


